export enum BusStatus {
  ACTIVE = "ACTIVE",
  IN_MAINTENANCE = "IN_MAINTENANCE",
  OUT_OF_SERVICE = "OUT_OF_SERVICE",
  IN_TRANSIT = "IN_TRANSIT",
  AVAILABLE = "AVAILABLE",
  CLEANING= "CLEANING",
}
